const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
async function api(path,opt={}){const r=await fetch(getWebAppBackendUrl(path),opt);const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}
let runs=[],ctx={};
function options(el,items,val='run_id',lab='run_id'){el.innerHTML=items.map(x=>`<option value="${x[val]}">${x[lab]}</option>`).join('')}
function bars(el,rows,key='weighted_ecl',name='product_type'){const max=Math.max(...rows.map(x=>Math.abs(x[key])),1);el.innerHTML=rows.map(x=>`<div class="bar"><span>${x[name]}</span><div class="track"><div class="fill" style="width:${Math.abs(x[key])/max*100}%"></div></div><b>${money(x[key])}</b></div>`).join('')}
async function load(){ctx=await api('/context');runs=await api('/runs');$('#status').textContent='Connected to Dataiku project';options($('#ov-run'),runs);options($('#from'),runs);options($('#to'),runs);$('#to').value=runs[0]?.run_id||'';$('#from').value=runs.find(x=>x.as_of_date==='2026-07-31')?.run_id||runs[1]?.run_id||'';$('#asof').innerHTML=ctx.as_of_dates.map(x=>`<option>${x}</option>`).join('');$('#asof').value=ctx.as_of_dates.at(-1);$('#models').innerHTML=ctx.models.length?`Saved Models discovered: ${ctx.models.map(x=>x.name).join(', ')}`:'No Saved Models discovered yet — formula fallback is ready.';renderVersions();await overview()}
async function overview(){const j=await api('/overview/'+encodeURIComponent($('#ov-run').value));const m=j.meta;$('#k-exp').textContent=money(m.total_exposure);$('#k-ecl').textContent=money(m.total_ecl);$('#k-cov').textContent=(100*m.total_ecl/m.total_exposure).toFixed(2)+'%';$('#k-n').textContent=j.instruments.toLocaleString();bars($('#p-bars'),j.portfolio);bars($('#s-bars'),j.stage,'weighted_ecl','stage');$('#top').innerHTML=j.top.map(x=>`<tr><td>${x.instrument_id}</td><td>${x.product_type}</td><td>${x.stage}</td><td>${money(x.ead)}</td><td>${money(x.ecl)}</td></tr>`).join('')}
function renderVersions(){$('#versions-body').innerHTML=runs.map(x=>`<tr><td>${x.run_id}</td><td>${x.as_of_date}</td><td><span class="pill">${x.status}</span></td><td>${money(x.total_ecl)}</td><td>${x.solution_bundle_version||''}</td><td>${x.status==='PRODUCTION'?'':`<button data-promote="${x.run_id}">Promote</button>`}</td></tr>`).join('');$$('[data-promote]').forEach(b=>b.onclick=()=>promote(b.dataset.promote))}
async function promote(id){await api('/promote/'+encodeURIComponent(id),{method:'POST'});$('#msg').textContent=`${id} promoted; prior official version was superseded.`;await load()}
async function compare(){const j=await api('/compare?from='+encodeURIComponent($('#from').value)+'&to='+encodeURIComponent($('#to').value));const top=j.rows.filter(x=>x.level===1),max=Math.max(...top.map(x=>Math.abs(x.amount)),1);$('#waterfall').innerHTML=`<div class="water">${top.map(x=>`<div class="witem"><div class="wbar ${x.amount>=0?'pos':'neg'}" data-cat="${x.category}" style="height:${45+150*Math.abs(x.amount)/max}px"></div><b>${money(x.amount)}</b><small>${x.category}</small></div>`).join('')}</div>`;$('#narrative').textContent=`ECL moved from ${money(j.from_ecl)} to ${money(j.to_ecl)}, a change of ${money(j.delta)}. Click a waterfall bar to drill into the seeded attribution.`;$$('[data-cat]').forEach(b=>b.onclick=()=>drill(b.dataset.cat,j.rows));drill('Macroeconomic scenario paths',j.rows)}
function drill(cat,rows){let z=rows.filter(x=>x.level===2&&x.parent_category===cat);if(!z.length)return;$('#drill-title').textContent=cat;bars($('#drill'),z,'amount','category');$$('#drill .bar').forEach((el,i)=>{const r=z[i];const deep=rows.filter(x=>x.level===3&&x.parent_category===`${cat}::${r.category}`);if(deep.length)el.style.cursor='pointer',el.onclick=()=>{$('#drill-title').textContent=`${cat} — ${r.category}`;bars($('#drill'),deep,'amount','category')}})}
async function run(){const b=Number($('#wb').value)/100,d=Number($('#wd').value)/100,s=Number($('#ws').value)/100;if(Math.abs(b+d+s-1)>.001){$('#msg').textContent='Scenario weights must total 100%.';return}const cfg={framework:$('#framework').value,as_of_date:$('#asof').value,weights:{Baseline:b,Downside:d,Severe:s},stage2_dpd:Number($('#s2').value),stage3_dpd:Number($('#s3').value),management_overlay:Number($('#overlay').value),bundle_version:$('#bundle').value,parent_run_id:$('#ov-run').value};const j=await api('/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});$('#run-result').innerHTML=`<p><b>${j.run_id}</b> saved as SANDBOX — ECL ${money(j.total_ecl)}</p>`;$('#msg').textContent='New immutable sandbox version created.';await load();$('#ov-run').value=j.run_id}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#refresh').onclick=overview;$('#ov-run').onchange=overview;$('#cmp').onclick=compare;$('#run').onclick=run;load().catch(e=>{$('#status').textContent='Connection error';$('#msg').textContent=e.message});
