const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
const pct=n=>(100*Number(n||0)).toFixed(1)+'%';
async function api(path,opt={}){const r=await fetch(getWebAppBackendUrl(path),opt);const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}
let runs=[],ctx={},methodCatalog={},methodRows=[],mathRows=[],readiness={},govRunId='';
function showMsg(t,bad=false){$('#msg').textContent=t||'';$('#msg').style.color=bad?'#a52a2a':'#18794e'}
function tab(name){$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===name))}
function runLabel(r){return `${r.run_label||r.run_id} · ${r.as_of_date||''} · ${r.status||''}`}
function fillRunOptions(el,selected){el.innerHTML=runs.map(r=>`<option value="${r.run_id}">${runLabel(r)}</option>`).join('');if(selected&&runs.some(r=>r.run_id===selected))el.value=selected}
function pill(status){return `<span class="pill ${(status||'').toLowerCase()}">${status||'-'}</span>`}
function bars(el,rows,key='weighted_ecl',name='product_type',formatter=money){if(!rows||!rows.length){el.innerHTML='<div class="hint">No data</div>';return}const max=Math.max(...rows.map(x=>Math.abs(Number(x[key]||0))),1);el.innerHTML=rows.map(x=>`<div class="bar"><span>${x[name]}</span><div class="track"><div class="fill" style="width:${Math.abs(Number(x[key]||0))/max*100}%"></div></div><b>${formatter(x[key])}</b></div>`).join('')}
function optionList(items,value,label,blank=''){return `${blank?`<option value="">${blank}</option>`:''}${items.map(x=>`<option value="${x[value]}">${x[label]}</option>`).join('')}`}
function fieldOptions(selected){const vals=['ALL',...(ctx.category_fields||[])];return vals.map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}

async function load(){
  [ctx,runs,methodCatalog,readiness]=await Promise.all([api('/context'),api('/runs'),api('/methodologies'),api('/engine-readiness')]);
  $('#status').textContent='Connected to Dataiku project';
  [$('#ov-run'),$('#from'),$('#to'),$('#parent-run'),$('#gov-run')].forEach(x=>fillRunOptions(x));
  if(runs.length){$('#to').value=runs[0].run_id;const j=runs.find(x=>x.as_of_date==='2026-07-31'&&x.status==='PRODUCTION');$('#from').value=(j||runs[1]||runs[0]).run_id;$('#parent-run').value=(runs.find(x=>x.status==='PRODUCTION')||runs[0]).run_id;}
  $('#asof').innerHTML=ctx.as_of_dates.map(x=>`<option>${x}</option>`).join('');$('#asof').value=ctx.as_of_dates.at(-1)||'';
  $('#vf-asof').innerHTML='<option value="">All</option>'+ctx.as_of_dates.slice().reverse().map(x=>`<option>${x}</option>`).join('');
  const mv=methodCatalog.config_versions||[];['method-config-version','method-version'].forEach(id=>$('#'+id).innerHTML=mv.map(x=>`<option>${x}</option>`).join(''));
  const math=ctx.math_config_versions||[];['math-config-version','math-version'].forEach(id=>$('#'+id).innerHTML=math.map(x=>`<option>${x}</option>`).join(''));
  const ep=ctx.execution_profiles||[];$('#execution-profile').innerHTML=ep.map(x=>`<option value="${x.profile_id}">${x.profile_label}</option>`).join('');
  $('#models').textContent=ctx.models.length?`Saved Models discovered: ${ctx.models.map(x=>x.name).join(', ')}`:'No Saved Models discovered yet — Saved Model selections will visibly fall back to the deterministic demo method.';
  renderReadiness(); populateCatalogSelectors(); renderVersions();
  if(runs.length){await overview();await loadGovern(runs[0].run_id)}
  if(mv.length){await loadMethodConfig(mv[0]);renderMethodSummary(mv[0])}
  if(math.length)await loadMath(math[0]);
}

function renderReadiness(){const sql=readiness.base_sql_ready?'Base portfolio/counterparty are SQL-backed on one connection.':'Base datasets are not detected as same-connection SQL tables.';$('#execution-readiness').textContent=`${sql} Current package always has a safe DSS Python fallback.`;const ds=(readiness.datasets||[]).map(x=>`<tr><td>${x.dataset}</td><td>${x.sql_table?'SQL':'DSS/non-SQL'}</td><td>${x.connection||'-'}</td></tr>`).join('');$('#engine-readiness-detail').innerHTML=`<p><b>${sql}</b></p><div class="table-scroll"><table><thead><tr><th>Dataset</th><th>Type</th><th>Connection</th></tr></thead><tbody>${ds}</tbody></table></div><p class="hint">Configured DSS scenarios detected: ${(readiness.scenario_ids||[]).join(', ')||'none'}</p>`}

async function overview(){const id=$('#ov-run').value;if(!id)return;const j=await api('/overview/'+encodeURIComponent(id)),m=j.meta;$('#k-exp').textContent=money(m.total_exposure);$('#k-ecl').textContent=money(m.total_ecl);$('#k-cov').textContent=(100*Number(m.total_ecl||0)/Math.max(Number(m.total_exposure||1),1)).toFixed(2)+'%';$('#k-n').textContent=Number(j.instruments||0).toLocaleString();$('#k-date').textContent=m.as_of_date||'';$('#k-status').textContent=m.status||'';const ob=$('#official-banner');if(Number(m.is_official)===1||m.status==='PRODUCTION'){ob.classList.remove('hidden');ob.textContent=`★ Official ${m.framework||''} version for ${m.as_of_date} — ${m.run_label||m.run_id}`;}else ob.classList.add('hidden');const eb=$('#engine-banner');if(m.requested_execution_engine||m.actual_execution_engine){eb.classList.remove('hidden');eb.textContent=`Execution: requested ${m.requested_execution_engine||'-'} → actual ${m.actual_execution_engine||'-'}. ${m.execution_note||''}`;}else eb.classList.add('hidden');bars($('#p-bars'),j.portfolio);bars($('#s-bars'),j.stage,'weighted_ecl','stage');bars($('#scenario-bars'),j.scenario,'scenario_ecl','scenario',money);bars($('#method-bars'),j.methods||[],'weighted_ecl','pd_method',money);$('#top').innerHTML=(j.top||[]).map(x=>`<tr><td>${x.instrument_id}</td><td>${x.product_type}</td><td>${x.stage}</td><td>${money(x.ead)}</td><td><b>${money(x.ecl)}</b></td></tr>`).join('')}

function renderVersions(){const fw=$('#vf-framework')?.value||'',asof=$('#vf-asof')?.value||'',st=$('#vf-status')?.value||'';const z=runs.filter(r=>(!fw||r.framework===fw)&&(!asof||r.as_of_date===asof)&&(!st||r.status===st));$('#versions-body').innerHTML=z.map(r=>{const official=Number(r.is_official)===1||r.status==='PRODUCTION',gov=r.govern_status||'—',git=r.git_status?`${r.provider||''} ${r.commit_hash||''}`:'—',eng=r.actual_execution_engine||r.requested_execution_engine||'—';return `<tr><td><div class="run-title">${r.run_label||r.run_id}</div><div class="run-id">${r.run_id}</div></td><td>${r.as_of_date||''}</td><td>${r.framework||''}</td><td>${pill(r.status)}</td><td>${official?'★ Yes':'—'}</td><td>${money(r.total_ecl)}</td><td>${r.method_config_version||'—'}</td><td>${r.math_config_version||'—'}</td><td>${eng}</td><td>${gov}</td><td>${git}</td><td><div class="action-group"><button data-view="${r.run_id}">View</button><button data-clone="${r.run_id}">Clone</button><button data-release="${r.run_id}">Release</button>${official?'':`<button data-official="${r.run_id}">Make official</button>`}</div></td></tr>`}).join('');$$('[data-view]').forEach(b=>b.onclick=()=>{tab('overview');$('#ov-run').value=b.dataset.view;overview()});$$('[data-clone]').forEach(b=>b.onclick=()=>cloneRun(b.dataset.clone));$$('[data-release]').forEach(b=>b.onclick=()=>openRelease(b.dataset.release));$$('[data-official]').forEach(b=>b.onclick=()=>promote(b.dataset.official))}
function cloneRun(id){const r=runs.find(x=>x.run_id===id);if(!r)return;tab('configure');$('#parent-run').value=id;$('#framework').value=r.framework||'IFRS9';$('#asof').value=r.as_of_date||'';$('#run-label').value=`Clone of ${r.run_label||id}`;if(r.baseline_weight!=null){$('#wb').value=Number(r.baseline_weight)*100;$('#wd').value=Number(r.downside_weight)*100;$('#ws').value=Number(r.severe_weight)*100}if(r.method_config_version&&[...$('#method-config-version').options].some(o=>o.value===r.method_config_version))$('#method-config-version').value=r.method_config_version;if(r.math_config_version&&[...$('#math-config-version').options].some(o=>o.value===r.math_config_version))$('#math-config-version').value=r.math_config_version;showMsg(`Cloned ${r.run_label||id} into a new draft configuration.`)}
async function promote(id){try{await api('/promote/'+encodeURIComponent(id),{method:'POST'});showMsg(`${id} is now official; the prior official version for the same framework/as-of was superseded.`);await reloadRuns()}catch(e){showMsg(e.message,true)}}
async function reloadRuns(){runs=await api('/runs');fillRunOptions($('#ov-run'),$('#ov-run').value);fillRunOptions($('#from'),$('#from').value);fillRunOptions($('#to'),$('#to').value);fillRunOptions($('#parent-run'),$('#parent-run').value);fillRunOptions($('#gov-run'),$('#gov-run').value);renderVersions()}

async function run(){const b=Number($('#wb').value)/100,d=Number($('#wd').value)/100,s=Number($('#ws').value)/100;if(Math.abs(b+d+s-1)>.001){showMsg('Scenario weights must total 100%.',true);return}const cfg={run_label:$('#run-label').value,framework:$('#framework').value,as_of_date:$('#asof').value,parent_run_id:$('#parent-run').value,bundle_version:$('#bundle').value,weights:{Baseline:b,Downside:d,Severe:s},stage2_dpd:Number($('#s2').value),stage3_dpd:Number($('#s3').value),reasonable_supportable_months:Number($('#rs').value),reversion_method:$('#reversion').value,reversion_months:Number($('#rev-months').value),management_overlay:Number($('#overlay').value),method_config_version:$('#method-config-version').value,math_config_version:$('#math-config-version').value,execution_profile_id:$('#execution-profile').value};try{const j=await api('/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});$('#run-result').innerHTML=`<p><b>${j.run_label}</b> created as SANDBOX — ECL ${money(j.total_ecl)}<br><span class="hint">Requested engine: ${j.requested_execution_engine}; actual: ${j.actual_execution_engine}. ${j.execution_note||''}</span></p>`;showMsg('New immutable sandbox version created.');await reloadRuns();$('#ov-run').value=j.run_id;$('#gov-run').value=j.run_id}catch(e){showMsg(e.message,true)}}

async function compare(){const j=await api('/compare?from='+encodeURIComponent($('#from').value)+'&to='+encodeURIComponent($('#to').value));const top=(j.rows||[]).filter(x=>Number(x.level)===1),max=Math.max(...top.map(x=>Math.abs(Number(x.amount||0))),1);$('#waterfall').innerHTML=`<div class="water">${top.map(x=>`<div class="witem"><div class="wbar ${Number(x.amount)>=0?'pos':'neg'}" data-cat="${x.category}" style="height:${45+150*Math.abs(Number(x.amount||0))/max}px"></div><b>${money(x.amount)}</b><small>${x.category}</small></div>`).join('')}</div>`;$('#narrative').textContent=`ECL moved from ${money(j.from_ecl)} to ${money(j.to_ecl)}, a change of ${money(j.delta)}.`;$$('[data-cat]').forEach(b=>b.onclick=()=>drill(b.dataset.cat,j.rows));if(top[0])drill(top[0].category,j.rows)}
function drill(cat,rows){let z=(rows||[]).filter(x=>Number(x.level)===2&&x.parent_category===cat);$('#drill-title').textContent=cat;if(!z.length){$('#drill').innerHTML='<div class="hint">No deeper attribution is stored for this run pair.</div>';return}bars($('#drill'),z,'amount','category')}

function populateCatalogSelectors(){const pp=methodCatalog.prepayment_catalog||[],lp=methodCatalog.lifetime_pd_catalog||[],tm=methodCatalog.transition_catalog||[],fx=methodCatalog.fixed_catalog||[];$('#pp-curve').innerHTML=optionList(pp,'curve_id','curve_label');$('#lpd-curve').innerHTML=optionList(lp,'curve_id','curve_label');$('#tm-matrix').innerHTML=optionList(tm,'matrix_id','matrix_label');$('#fixed-set').innerHTML=optionList(fx,'parameter_set_id','parameter_set_label');if(pp.length)loadPP();if(lp.length)loadLPD();if(tm.length)loadTM();if(fx.length)loadFixed()}
async function loadMethodConfig(version){if(!version)return;methodRows=await api('/method-config/'+encodeURIComponent(version));renderMethodConfigRows()}
function sourcesFor(prod,type='PD_12M'){const fx=(methodCatalog.fixed_catalog||[]).filter(x=>(x.product_type===prod||x.product_type==='*')&&x.parameter_type===type).map(x=>({id:x.parameter_set_id,label:x.parameter_set_label}));const lp=(methodCatalog.lifetime_pd_catalog||[]).filter(x=>x.product_type===prod).map(x=>({id:x.curve_id,label:x.curve_label}));const mods=(ctx.models||[]).map(x=>({id:x.id,label:`Saved Model: ${x.name}`}));return [...fx,...lp,...mods]}
function renderMethodConfigRows(){const pp=methodCatalog.prepayment_catalog||[],tm=methodCatalog.transition_catalog||[];$('#method-config-body').innerHTML=methodRows.map((r,i)=>{const prod=r.product_type,pps=pp.filter(x=>x.product_type===prod),tms=tm.filter(x=>x.product_type===prod),pdsrc=sourcesFor(prod),lgdsrc=sourcesFor(prod,'LGD'),eadsrc=sourcesFor(prod,'CCF');return `<tr data-method-row="${i}"><td><b>${prod}</b></td><td><select data-f="pd_method"><option>FORMULA</option><option>FIXED</option><option>SAVED_MODEL</option><option>LIFETIME_PD_CURVE</option><option>TRANSITION_MATRIX</option></select></td><td><select data-f="pd_source_id">${optionList(pdsrc,'id','label','None / formula')}</select></td><td><select data-f="pd_category_field">${fieldOptions(r.pd_category_field||'ALL')}</select></td><td><select data-f="transition_matrix_id">${optionList(tms,'matrix_id','matrix_label','None')}</select></td><td><select data-f="transition_state_field">${fieldOptions(r.transition_state_field||'ALL')}</select></td><td><select data-f="lgd_method"><option>FORMULA</option><option>FIXED</option><option>SAVED_MODEL</option></select></td><td><select data-f="lgd_source_id">${optionList(lgdsrc,'id','label','None / formula')}</select></td><td><select data-f="ead_method"><option>CONTRACTUAL</option><option>CCF_FIXED</option><option>SAVED_MODEL</option></select></td><td><select data-f="ead_source_id">${optionList(eadsrc,'id','label','None')}</select></td><td><select data-f="prepayment_method"><option>NONE</option><option>CURVE</option></select></td><td><select data-f="prepayment_curve_id">${optionList(pps,'curve_id','curve_label','None')}</select></td><td><select data-f="prepayment_category_field">${fieldOptions(r.prepayment_category_field||'ALL')}</select></td></tr>`}).join('');$$('[data-method-row]').forEach(tr=>{const i=Number(tr.dataset.methodRow),r=methodRows[i];[...tr.querySelectorAll('select')].forEach(s=>{if(r[s.dataset.f]!=null&&[...s.options].some(o=>o.value===String(r[s.dataset.f])))s.value=r[s.dataset.f];s.onchange=()=>r[s.dataset.f]=s.value})})}
function renderMethodSummary(version){api('/method-config/'+encodeURIComponent(version)).then(rows=>{const counts={};rows.forEach(r=>counts[r.pd_method]=(counts[r.pd_method]||0)+1);$('#method-summary').innerHTML=`<div class="mini-stats">${Object.entries(counts).map(([k,v])=>`<div><small>${k}</small><b>${v} portfolios</b></div>`).join('')}</div>`})}
async function saveMethodConfig(){const base=$('#method-version').value,version='METHODCFG_'+new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);try{const j=await api('/method-config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config_version:version,rows:methodRows,notes:`Cloned from ${base}`})});showMsg(`Saved methodology version ${j.config_version}.`);methodCatalog=await api('/methodologies');const vs=methodCatalog.config_versions;['method-version','method-config-version'].forEach(id=>$('#'+id).innerHTML=vs.map(x=>`<option>${x}</option>`).join(''));$('#method-version').value=j.config_version;$('#method-config-version').value=j.config_version;renderMethodSummary(j.config_version)}catch(e){showMsg(e.message,true)}}

function svgLine(rows,xKey,yKey,yFmt=v=>v){if(!rows||!rows.length)return '<div class="hint">No curve data</div>';const W=500,H=210,p=28,x=rows.map(r=>Number(r[xKey])),y=rows.map(r=>Number(r[yKey]));const xmin=Math.min(...x),xmax=Math.max(...x),ymax=Math.max(...y,1e-6),sx=v=>p+(v-xmin)/(Math.max(xmax-xmin,1))*(W-2*p),sy=v=>H-p-v/Math.max(ymax,1e-9)*(H-2*p),pts=x.map((v,i)=>`${sx(v)},${sy(y[i])}`).join(' ');return `<svg viewBox="0 0 ${W} ${H}"><line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" class="chart-axis"/><line x1="${p}" y1="${p}" x2="${p}" y2="${H-p}" class="chart-axis"/><polyline points="${pts}" class="chart-line"/><text x="${p}" y="${H-8}" class="chart-label">${xmin}</text><text x="${W-p-18}" y="${H-8}" class="chart-label">${xmax}</text><text x="4" y="${p+4}" class="chart-label">${yFmt(ymax)}</text></svg>`}
async function loadFixed(){const id=$('#fixed-set').value;if(!id)return;const rows=await api('/fixed-values?parameter_set_id='+encodeURIComponent(id)+'&scenario='+encodeURIComponent($('#fixed-scenario').value));$('#fixed-view').innerHTML=`<table><thead><tr><th>Parameter</th><th>Category field</th><th>Category</th><th>Value</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.parameter_type}</td><td>${r.category_field}</td><td>${r.category_value}</td><td>${Number(r.value).toFixed(4)}</td></tr>`).join('')}</tbody></table>`}
async function loadPP(){const id=$('#pp-curve').value;if(!id)return;const raw=await api('/curve/prepayment?curve_id='+encodeURIComponent(id)+'&scenario='+encodeURIComponent($('#pp-scenario').value));const cur=$('#pp-bucket').value;$('#pp-bucket').innerHTML=(raw.buckets||[]).map(x=>`<option>${x}</option>`).join('');if(cur&&(raw.buckets||[]).includes(cur))$('#pp-bucket').value=cur;const bucket=$('#pp-bucket').value;const rows=(raw.rows||[]).filter(r=>!bucket||r.bucket_value===bucket);$('#pp-chart').innerHTML=svgLine(rows,'month','annual_cpr',pct);const m12=rows.find(r=>Number(r.month)===12)||rows.at(-1),m60=rows.find(r=>Number(r.month)===60)||rows.at(-1);$('#pp-stats').innerHTML=`<div><small>12m CPR</small><b>${pct(m12?.annual_cpr)}</b></div><div><small>60m CPR</small><b>${pct(m60?.annual_cpr)}</b></div><div><small>Bucket</small><b>${bucket||'ALL'}</b></div>`}
async function loadLPD(){const id=$('#lpd-curve').value;if(!id)return;const raw=await api('/curve/lifetime-pd?curve_id='+encodeURIComponent(id)+'&scenario='+encodeURIComponent($('#lpd-scenario').value));const cur=$('#lpd-bucket').value;$('#lpd-bucket').innerHTML=(raw.buckets||[]).map(x=>`<option>${x}</option>`).join('');if(cur&&(raw.buckets||[]).includes(cur))$('#lpd-bucket').value=cur;const b=$('#lpd-bucket').value,rows=(raw.rows||[]).filter(r=>r.risk_bucket===b);$('#lpd-chart').innerHTML=svgLine(rows,'month','cumulative_pd',pct);const m12=rows.find(r=>Number(r.month)===12)||rows.at(-1),m60=rows.find(r=>Number(r.month)===60)||rows.at(-1);$('#lpd-stats').innerHTML=`<div><small>12m cumulative PD</small><b>${pct(m12?.cumulative_pd)}</b></div><div><small>60m cumulative PD</small><b>${pct(m60?.cumulative_pd)}</b></div><div><small>Bucket</small><b>${b||'-'}</b></div>`}
async function loadTM(){const id=$('#tm-matrix').value;if(!id)return;const rows=await api('/matrix?matrix_id='+encodeURIComponent(id)+'&scenario='+encodeURIComponent($('#tm-scenario').value));const states=[...new Set(rows.map(r=>r.from_state))],tos=[...new Set(rows.map(r=>r.to_state))];$('#matrix-field').textContent=rows[0]?`State comes from loan/counterparty field: ${rows[0].state_field}`:'';let h='<table class="matrix-table"><thead><tr><th>From / To</th>'+tos.map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>';states.forEach(fs=>{h+=`<tr><td>${fs}</td>`+tos.map(ts=>{const r=rows.find(x=>x.from_state===fs&&x.to_state===ts);return `<td>${pct(r?.annual_probability)}</td>`}).join('')+'</tr>'});h+='</tbody></table>';$('#matrix-view').innerHTML=h}

async function loadMath(version){if(!version)return;const j=await api('/math-configs?version='+encodeURIComponent(version));mathRows=j.rows||[];$('#math-body').innerHTML=mathRows.map(r=>`<tr><td><b>${r.product_type}</b></td><td>${r.loop_level}</td><td>${r.parent_key}</td><td>${r.entity_key}</td><td>${r.child_key||'-'}</td><td>${r.time_step}</td><td>${r.horizon_method}</td><td>${r.pd_application}</td><td>${r.discount_method}<div class="run-id">${r.discount_rate_field}</div></td><td><code>${r.ecl_formula}</code></td></tr>`).join('')}

async function openRelease(id){tab('governance');$('#gov-run').value=id;await loadGovern(id)}
async function loadGovern(id){govRunId=id||$('#gov-run').value;if(!govRunId)return;const j=await api('/govern/'+encodeURIComponent(govRunId));const g=j.governance||{},r=j.release;$('#gov-artifact').innerHTML=`<b>${g.mock_artifact_id||'No Govern artifact yet'}</b><div class="hint">Status: ${g.govern_status||'NOT_SUBMITTED'} · Mode: MOCK</div>`;const st=g.govern_status||'NOT_SUBMITTED',steps=['SANDBOX','REVIEW','APPROVED','PRODUCTION'],run=runs.find(x=>x.run_id===govRunId),current=run?.status==='PRODUCTION'?'PRODUCTION':st,done=s=>steps.indexOf(s)<=steps.indexOf(current)&&steps.indexOf(current)>=0;$('#gov-workflow').innerHTML=steps.map(s=>`<div class="workflow-step ${done(s)?'done':''} ${s===current?'active':''}">${s}</div>`).join('');$('#git-status').innerHTML=r?`<div class="artifact-card"><b>${r.provider} mock push</b><div class="hint">${r.repository} · ${r.branch}<br>${r.commit_hash} · ${r.status}</div></div>`:'<div class="hint">No release manifest pushed yet.</div>';const mf=await api('/release-manifest/'+encodeURIComponent(govRunId));$('#manifest-preview').textContent=JSON.stringify(mf,null,2)}
async function governAction(action){if(!govRunId)return;try{const j=await api(`/govern/${action}/`+encodeURIComponent(govRunId),{method:'POST'});showMsg(`Mock Govern status: ${j.govern_status}`);await reloadRuns();await loadGovern(govRunId)}catch(e){showMsg(e.message,true)}}
async function gitPush(){if(!govRunId)return;try{const j=await api('/release/push/'+encodeURIComponent(govRunId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:$('#git-provider').value,repository:$('#git-repo').value,branch:$('#git-branch').value})});showMsg(`Mock ${j.provider} push created commit ${j.commit_hash}. No external repository was changed.`);await reloadRuns();await loadGovern(govRunId)}catch(e){showMsg(e.message,true)}}
async function downloadManifest(){if(!govRunId)return;const mf=await api('/release-manifest/'+encodeURIComponent(govRunId));const blob=new Blob([JSON.stringify(mf,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${govRunId}.json`;a.click();URL.revokeObjectURL(a.href)}

$$('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#refresh').onclick=overview;$('#ov-run').onchange=overview;$('#run').onclick=run;$('#cmp').onclick=compare;$('#versions-refresh').onclick=reloadRuns;['vf-framework','vf-asof','vf-status'].forEach(id=>$('#'+id).onchange=renderVersions);$('#method-version').onchange=()=>loadMethodConfig($('#method-version').value);$('#save-method-config').onclick=saveMethodConfig;$('#method-config-version').onchange=()=>renderMethodSummary($('#method-config-version').value);$('#fixed-set').onchange=loadFixed;$('#fixed-scenario').onchange=loadFixed;$('#pp-curve').onchange=loadPP;$('#pp-scenario').onchange=loadPP;$('#pp-bucket').onchange=loadPP;$('#lpd-curve').onchange=loadLPD;$('#lpd-scenario').onchange=loadLPD;$('#lpd-bucket').onchange=loadLPD;$('#tm-matrix').onchange=loadTM;$('#tm-scenario').onchange=loadTM;$('#math-version').onchange=()=>loadMath($('#math-version').value);$('#gov-run').onchange=()=>loadGovern($('#gov-run').value);$('#gov-refresh').onclick=()=>loadGovern($('#gov-run').value);$('#gov-submit').onclick=()=>governAction('submit');$('#gov-approve').onclick=()=>governAction('approve');$('#gov-reject').onclick=()=>governAction('reject');$('#git-push').onclick=gitPush;$('#download-manifest').onclick=downloadManifest;
load().catch(e=>{$('#status').textContent='Connection error';showMsg(e.message,true)});
